In [1]:
!wget https://github.com/TheSSJ2612/Real-Time-Medical-Mask-Detection/releases/download/v0.1/Dataset.zip

--2023-11-01 19:37:22--  https://github.com/TheSSJ2612/Real-Time-Medical-Mask-Detection/releases/download/v0.1/Dataset.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/271334712/b03ea500-ab6a-11ea-8e77-36ffeab09a82?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20231101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231101T193722Z&X-Amz-Expires=300&X-Amz-Signature=0844a267da9ec7ec856ea95c985b62199c51f95980d7a5f3e5d111dc5b28bc72&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=271334712&response-content-disposition=attachment%3B%20filename%3DDataset.zip&response-content-type=application%2Foctet-stream [following]
--2023-11-01 19:37:22--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/271334712/b03ea500-ab6a-11ea-8e77-36ff

In [2]:
!unzip Dataset.zip

Streaming output truncated to the last 5000 lines.
  inflating: Dataset/with_mask/1467.jpg  
  inflating: Dataset/with_mask/1468.jpg  
  inflating: Dataset/with_mask/1469.jpg  
  inflating: Dataset/with_mask/147.jpg  
  inflating: Dataset/with_mask/1470.jpg  
  inflating: Dataset/with_mask/1471.jpg  
  inflating: Dataset/with_mask/1472.jpg  
  inflating: Dataset/with_mask/1473.jpg  
  inflating: Dataset/with_mask/1474.jpg  
  inflating: Dataset/with_mask/1475.jpg  
  inflating: Dataset/with_mask/1476.jpg  
  inflating: Dataset/with_mask/1477.jpg  
  inflating: Dataset/with_mask/1478.jpg  
  inflating: Dataset/with_mask/1479.jpg  
  inflating: Dataset/with_mask/148.jpg  
  inflating: Dataset/with_mask/1480.jpg  
  inflating: Dataset/with_mask/1481.jpg  
  inflating: Dataset/with_mask/1482.jpg  
  inflating: Dataset/with_mask/1483.jpg  
  inflating: Dataset/with_mask/1484.jpg  
  inflating: Dataset/with_mask/1485.jpg  
  inflating: Dataset/with_mask/1486.jpg  
  inflating: Dataset/with_m

In [3]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import numpy as np
import pandas as pd
import cv2
import os
import h5py
import pickle

In [4]:
train_labels = os.listdir('Dataset')
train_labels

['without_mask', 'with_mask']

In [5]:
train_labels.sort()
train_labels

['with_mask', 'without_mask']

In [6]:
X = []
y = []
for label in train_labels:
    dir = os.path.join('Dataset', label)
    current_label = label
    print('Current Folder: ' + current_label)
    for x in range(1, 5521):
        print('Current Image: ' + str(x))
        file = os.path.join(dir, str(x) + '.jpg')
        image = cv2.imread(file)
        image = cv2.resize(image, (500, 500))
        image_hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        hist = cv2.calcHist([image], [0, 1, 2], None, [8, 8, 8], [0, 256, 0, 256, 0, 256])
        cv2.normalize(hist, hist)
        histogram_features = hist.flatten()
        image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        hue_features = cv2.HuMoments(cv2.moments(image_gray)).flatten()
        current_features = np.hstack([histogram_features, hue_features])
        X.append(current_features)
        y.append(current_label)

Streaming output truncated to the last 5000 lines.
Current Image: 521
Current Image: 522
Current Image: 523
Current Image: 524
Current Image: 525
Current Image: 526
Current Image: 527
Current Image: 528
Current Image: 529
Current Image: 530
Current Image: 531
Current Image: 532
Current Image: 533
Current Image: 534
Current Image: 535
Current Image: 536
Current Image: 537
Current Image: 538
Current Image: 539
Current Image: 540
Current Image: 541
Current Image: 542
Current Image: 543
Current Image: 544
Current Image: 545
Current Image: 546
Current Image: 547
Current Image: 548
Current Image: 549
Current Image: 550
Current Image: 551
Current Image: 552
Current Image: 553
Current Image: 554
Current Image: 555
Current Image: 556
Current Image: 557
Current Image: 558
Current Image: 559
Current Image: 560
Current Image: 561
Current Image: 562
Current Image: 563
Current Image: 564
Current Image: 565
Current Image: 566
Current Image: 567
Current Image: 568
Current Image: 569
Current Image: 570

In [7]:
np.shape(X)

(11040, 519)

In [8]:
np.shape(y)

(11040,)

In [11]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
mms = MinMaxScaler()
X_train = mms.fit_transform(X_train)
X_train

array([[1.73569027e-01, 1.96871580e-01, 1.24336102e-02, ...,
        2.45087858e-17, 6.44921540e-02, 2.20697204e-16],
       [1.07532649e-01, 5.04784559e-02, 5.72998732e-03, ...,
        2.45087266e-17, 6.45062021e-02, 2.20697100e-16],
       [3.53763625e-03, 3.58690379e-02, 5.77206366e-03, ...,
        2.45087697e-17, 6.44955521e-02, 2.20697273e-16],
       ...,
       [5.48753028e-04, 1.35180066e-03, 0.00000000e+00, ...,
        2.45047778e-17, 6.44243271e-02, 2.20698536e-16],
       [2.58077456e-01, 7.97347869e-02, 6.31672099e-05, ...,
        2.45087895e-17, 6.44928933e-02, 2.20697203e-16],
       [1.74620847e-01, 3.37255855e-02, 0.00000000e+00, ...,
        2.45087674e-17, 6.45015049e-02, 2.20697183e-16]])

In [17]:
!pip install xgboost

In [18]:
import xgboost as xgb
import numpy as np
from xgboost import XGBClassifier

In [19]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [20]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, ..., 1, 1, 1])

In [21]:
from sklearn import metrics

In [22]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90      1388
           1       0.91      0.89      0.90      1372

    accuracy                           0.90      2760
   macro avg       0.90      0.90      0.90      2760
weighted avg       0.90      0.90      0.90      2760

